testing 3

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -47,9 +47,11 @@ jobs:
             dotnet list "$proj" package --vulnerable
 
             # Check the code formatting
-            echo "Check the code formatting for $proj"
-            dotnet format --verify-no-changes "$proj"
+            set +e   # allow non-zero exit codes
+            dotnet format --verify-no-changes
             EXIT_CODE=$?
+            set -e   # re-enable fail-fast for later steps
+
             if [ $EXIT_CODE -ne 0 ]; then
               echo "⚠️ Code formatting issues found in the '$proj' project, but not failing the build."
             fi
